# Generated by Django 3.1.6 on 2021-03-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default=11, help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)", max_length=200),
            preserve_default=False,
        ),
    ]
