# Generated by Django 3.1.7 on 2021-03-11 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
