# Generated by Django 3.1.7 on 2021-03-12 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_tmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tmodel',
            name='for_inline',
        ),
        migrations.RemoveField(
            model_name='tmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tmodel',
            name='owner',
        ),
        migrations.AlterField(
            model_name='tmodel',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.tmodel'),
        ),
    ]
