# Generated by Django 3.1.7 on 2021-03-12 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20210312_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tmodel',
            old_name='test',
            new_name='search',
        ),
    ]
