# Generated by Django 3.1.7 on 2021-03-16 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20210314_1053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TModel',
        ),
    ]
