# Generated by Django 3.1.7 on 2021-03-16 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20210316_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='TModelAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.tmodelauthor')),
            ],
        ),
        migrations.CreateModel(
            name='TModelBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.tmodelbook')),
            ],
        ),
        migrations.DeleteModel(
            name='TModel',
        ),
    ]
